// Generated by scripts/make-privacy.mjs from store/privacy-policy.md — do not edit by hand.
//
// The policy ships inside the extension so the in-product link works with no
// network and no hosting, and so there is exactly one copy of the text.

export type Span = { t: 'text' | 'strong' | 'code'; v: string }

export type Block =
  | { kind: 'h1' | 'h2' | 'h3' | 'p' | 'meta'; spans: Span[] }
  | { kind: 'ul'; items: Span[][] }

export const POLICY: Block[] = [
  {
    "kind": "h1",
    "spans": [
      {
        "t": "text",
        "v": "StackLens Privacy Policy"
      }
    ]
  },
  {
    "kind": "meta",
    "spans": [
      {
        "t": "text",
        "v": "Last updated: 2026-07-25"
      }
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "The short version"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "StackLens does not collect, transmit, or sell any data. There is no account, no server, and no analytics. Everything it reads is analysed on your own device."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "One feature stores data beyond the current session: "
      },
      {
        "t": "strong",
        "v": "scan history"
      },
      {
        "t": "text",
        "v": ", which remembers what each site you visit was built with. It is stored only on your device, is never transmitted, can be cleared at any time, and can be switched off entirely. It is described in full below."
      }
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "What StackLens reads"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "To identify the technologies a website is built with, StackLens observes the following about pages you visit, all of which is information any visitor can see using the browser's built-in developer tools:"
      }
    ]
  },
  {
    "kind": "ul",
    "items": [
      [
        {
          "t": "strong",
          "v": "Request URLs"
        },
        {
          "t": "text",
          "v": " the page makes — the host, path, and query string. Request and response bodies are never read."
        }
      ],
      [
        {
          "t": "strong",
          "v": "Response headers"
        },
        {
          "t": "text",
          "v": " of the main document, such as "
        },
        {
          "t": "code",
          "v": "Server"
        },
        {
          "t": "text",
          "v": " and "
        },
        {
          "t": "code",
          "v": "X-Powered-By"
        },
        {
          "t": "text",
          "v": "."
        }
      ],
      [
        {
          "t": "strong",
          "v": "Cookie names"
        },
        {
          "t": "text",
          "v": " for the site's own origin. Cookie "
        },
        {
          "t": "strong",
          "v": "values are never read or stored"
        },
        {
          "t": "text",
          "v": " — only the name is needed to identify a service."
        }
      ],
      [
        {
          "t": "strong",
          "v": "Script URLs, meta tags, and page markup"
        },
        {
          "t": "text",
          "v": "."
        }
      ],
      [
        {
          "t": "strong",
          "v": "Names of JavaScript variables"
        },
        {
          "t": "text",
          "v": " the page defines on "
        },
        {
          "t": "code",
          "v": "window"
        },
        {
          "t": "text",
          "v": "."
        }
      ],
      [
        {
          "t": "strong",
          "v": "Keys"
        },
        {
          "t": "text",
          "v": " stored in local and session storage. Stored "
        },
        {
          "t": "strong",
          "v": "values are never read"
        },
        {
          "t": "text",
          "v": "."
        }
      ]
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "Deep scan"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "The \"Deep scan\" button is optional and never runs on its own. When you press it, StackLens downloads the JavaScript files the page already loaded and searches that text for identifying strings, such as a package name or a model name."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "That downloaded code is "
      },
      {
        "t": "strong",
        "v": "only ever read as text"
      },
      {
        "t": "text",
        "v": ". It is never executed, evaluated, or injected into any page."
      }
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "What StackLens sends"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "Nothing."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "There is no remote server, no telemetry, no crash reporting, and no advertising identifier. The extension makes no network requests of its own except:"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "1. The optional deep scan described above, which fetches files from the site you are already viewing. 2. A single cache-first request for the current page's headers, used only when the browser started the page load before the extension was ready to observe it. This is served from your browser cache in the normal case."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "Brand logos are bundled inside the extension rather than fetched from a CDN, specifically so that no third party ever learns which sites you scan."
      }
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "Where data is stored"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "Detection results are held in your browser's session storage, scoped to the tab they belong to. They are deleted when you close the tab and when you close the browser."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "strong",
        "v": "Scan history"
      },
      {
        "t": "text",
        "v": ", when enabled, is stored in local extension storage and persists until cleared. Each entry holds a site's domain and origin, the time it was last scanned, and the names of the technologies detected. It does "
      },
      {
        "t": "strong",
        "v": "not"
      },
      {
        "t": "text",
        "v": " store page paths, page content, request logs, cookies, or anything you typed — only what the panel already showed you. One entry is kept per site rather than one per visit, so it is a record of what sites are built with rather than a log of your browsing."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "History is on by default, can be switched off in Settings or on the History page, and switching it off deletes everything already stored. Individual sites can be forgotten, and the whole list cleared, from the History page."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "Your settings — whether scanning is on, whether history is on, and which sites you have turned scanning off for — are stored locally on your device."
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "None of this is ever transmitted anywhere."
      }
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "Your controls"
      }
    ]
  },
  {
    "kind": "ul",
    "items": [
      [
        {
          "t": "text",
          "v": "Turn scanning off entirely from the settings page."
        }
      ],
      [
        {
          "t": "text",
          "v": "Turn it off for individual sites; StackLens then collects nothing on them and discards anything it had already collected for that site."
        }
      ],
      [
        {
          "t": "text",
          "v": "Turn scan history off, clear it entirely, or forget individual sites."
        }
      ],
      [
        {
          "t": "text",
          "v": "Uninstalling the extension removes all stored data."
        }
      ]
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "Permissions and why each is needed"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "See "
      },
      {
        "t": "code",
        "v": "permissions.md"
      },
      {
        "t": "text",
        "v": " in this directory for the justification of each permission requested."
      }
    ]
  },
  {
    "kind": "h2",
    "spans": [
      {
        "t": "text",
        "v": "Contact"
      }
    ]
  },
  {
    "kind": "p",
    "spans": [
      {
        "t": "text",
        "v": "Questions about this policy can be raised as an issue on the project repository."
      }
    ]
  }
]
