import type { Fingerprint } from '@/types'

/**
 * Live chat, support widgets, and help centres.
 *
 * Trivially detectable — a chat widget is a visible iframe or launcher element
 * injected into the page, backed by a WebSocket to the vendor.
 */
export const CHAT: Fingerprint[] = [
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'chat',
    description: 'Customer messaging and support',
    icon: 'intercom',
    website: 'https://intercom.com',
    signals: [
      { type: 'global', path: 'Intercom', weight: 0.95 },
      { type: 'request', pattern: /widget\.intercom\.io|(?:api|nexus)[\w-]*\.intercom\.io/, weight: 0.95 },
      { type: 'dom', selector: '#intercom-frame, .intercom-lightweight-app', weight: 0.9 },
    ],
  },
  {
    id: 'crisp',
    name: 'Crisp',
    category: 'chat',
    description: 'Live chat and shared inbox',
    icon: 'crisp',
    website: 'https://crisp.chat',
    signals: [
      { type: 'global', path: '$crisp', weight: 0.95 },
      { type: 'script', pattern: /client\.crisp\.chat/, weight: 0.95 },
      { type: 'dom', selector: '.crisp-client', weight: 0.9 },
    ],
  },
  {
    id: 'tidio',
    name: 'Tidio',
    category: 'chat',
    description: 'Live chat and chatbots',
    icon: 'tidio',
    website: 'https://tidio.com',
    signals: [
      { type: 'global', path: 'tidioChatApi', weight: 0.95 },
      { type: 'script', pattern: /code\.tidio\.co/, weight: 0.95 },
    ],
  },
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'chat',
    description: 'Support ticketing and messaging',
    icon: 'zendesk',
    website: 'https://zendesk.com',
    signals: [
      { type: 'global', path: 'zE', weight: 0.95 },
      { type: 'script', pattern: /static\.zdassets\.com|zendesk\.com\/embeddable/, weight: 0.95 },
      { type: 'request', pattern: /[\w-]+\.zendesk\.com/, weight: 0.85 },
    ],
  },
  {
    id: 'drift',
    name: 'Drift',
    category: 'chat',
    description: 'Conversational marketing and sales chat',
    icon: 'drift',
    website: 'https://drift.com',
    signals: [
      { type: 'global', path: 'drift', weight: 0.95 },
      { type: 'script', pattern: /js\.driftt\.com|driftt\.com\/include/, weight: 0.95 },
    ],
  },
  {
    id: 'front',
    name: 'Front',
    category: 'chat',
    description: 'Shared inbox and customer communication',
    icon: 'front',
    website: 'https://front.com',
    signals: [
      { type: 'global', path: 'FrontChat', weight: 0.95 },
      { type: 'script', pattern: /chat-assets\.frontapp\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'livechat',
    name: 'LiveChat',
    category: 'chat',
    description: 'Live chat and help desk',
    icon: 'livechat',
    website: 'https://livechat.com',
    signals: [
      { type: 'global', path: 'LiveChatWidget', weight: 0.95 },
      { type: 'script', pattern: /cdn\.livechatinc\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'chatwoot',
    name: 'Chatwoot',
    category: 'chat',
    description: 'Open-source customer engagement',
    icon: 'chatwoot',
    website: 'https://chatwoot.com',
    signals: [
      { type: 'global', path: '$chatwoot', weight: 0.95 },
      { type: 'script', pattern: /[\w-]*\.?chatwoot\.com\/packs|sdk\.js.{0,20}chatwoot/, weight: 0.9 },
    ],
  },
  {
    id: 'helpscout',
    name: 'Help Scout',
    category: 'chat',
    description: 'Help desk and knowledge base',
    icon: 'helpscout',
    website: 'https://helpscout.com',
    signals: [
      { type: 'global', path: 'Beacon', weight: 0.9 },
      { type: 'script', pattern: /beacon-v2\.helpscout\.net/, weight: 0.95 },
    ],
  },
  {
    id: 'plain',
    name: 'Plain',
    category: 'chat',
    description: 'Support for technical products',
    icon: 'plain',
    website: 'https://plain.com',
    signals: [
      { type: 'global', path: 'Plain', weight: 0.9 },
      { type: 'script', pattern: /chat\.cdn-plain\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'pylon',
    name: 'Pylon',
    category: 'chat',
    description: 'B2B customer support platform',
    icon: 'pylon',
    website: 'https://usepylon.com',
    signals: [
      { type: 'global', path: 'Pylon', weight: 0.9 },
      { type: 'script', pattern: /widget\.usepylon\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'canny',
    name: 'Canny',
    category: 'chat',
    description: 'Feedback and feature request boards',
    icon: 'canny',
    website: 'https://canny.io',
    signals: [
      { type: 'global', path: 'Canny', weight: 0.95 },
      { type: 'script', pattern: /canny\.io\/sdk\.js/, weight: 0.95 },
    ],
  },
  {
    id: 'tawkto',
    name: 'Tawk.to',
    category: 'chat',
    description: 'Free live chat widget',
    icon: 'tawkto',
    website: 'https://tawk.to',
    signals: [
      { type: 'global', path: 'Tawk_API', weight: 0.95 },
      { type: 'script', pattern: /embed\.tawk\.to/, weight: 0.95 },
    ],
  },
  {
    id: 'freshdesk',
    name: 'Freshworks',
    category: 'chat',
    description: 'Support desk and messaging',
    icon: 'freshworks',
    website: 'https://freshworks.com',
    signals: [
      { type: 'global', path: 'fwSettings', weight: 0.9 },
      { type: 'script', pattern: /widget\.freshworks\.com|wchat\.freshchat\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    category: 'chat',
    description: 'Support desk for ecommerce',
    icon: 'gorgias',
    website: 'https://gorgias.com',
    signals: [
      { type: 'global', path: 'GorgiasChat', weight: 0.95 },
      { type: 'script', pattern: /config\.gorgias\.chat|assets\.gorgias\.chat/, weight: 0.95 },
    ],
  },
  {
    id: 'olark',
    name: 'Olark',
    category: 'chat',
    description: 'Live chat',
    icon: 'olark',
    website: 'https://olark.com',
    signals: [
      { type: 'global', path: 'olark', weight: 0.95 },
      { type: 'script', pattern: /static\.olark\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'kustomer',
    name: 'Kustomer',
    category: 'chat',
    description: 'Customer service CRM',
    icon: 'kustomer',
    website: 'https://kustomer.com',
    signals: [
      { type: 'global', path: 'Kustomer', weight: 0.95 },
      { type: 'script', pattern: /cdn\.kustomerapp\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'ada-support',
    name: 'Ada',
    category: 'chat',
    description: 'AI customer service automation',
    icon: 'ada',
    website: 'https://ada.cx',
    signals: [
      { type: 'global', path: 'adaEmbed', weight: 0.95 },
      { type: 'script', pattern: /static\.ada\.support\/embed/, weight: 0.95 },
    ],
  },
  {
    id: 'sierra-ai',
    name: 'Sierra',
    category: 'chat',
    description: 'AI agents for customer support',
    icon: 'sierra',
    website: 'https://sierra.ai',
    signals: [
      { type: 'request', pattern: /(?:api|sdk)\.sierra\.ai|chat\.sierra\.ai/, weight: 0.95 },
    ],
  },
  {
    id: 'decagon',
    name: 'Decagon',
    category: 'chat',
    description: 'AI support agents',
    icon: 'decagon',
    website: 'https://decagon.ai',
    signals: [
      { type: 'script', pattern: /[\w-]*\.decagon\.ai\/[\w-]*(?:sdk|widget)/, weight: 0.95 },
    ],
  },
  {
    id: 'zoho-salesiq',
    name: 'Zoho SalesIQ',
    category: 'chat',
    description: 'Live chat and visitor tracking',
    icon: 'zoho',
    website: 'https://zoho.com/salesiq',
    signals: [
      { type: 'global', path: '$zoho.salesiq', weight: 0.95 },
      { type: 'script', pattern: /salesiq\.zoho(?:public)?\.(?:com|eu|in)/, weight: 0.95 },
    ],
  },
  {
    id: 'botpress',
    name: 'Botpress',
    category: 'chat',
    description: 'Open-source chatbot platform',
    icon: 'botpress',
    website: 'https://botpress.com',
    signals: [
      { type: 'global', path: 'botpress', weight: 0.9 },
      { type: 'script', pattern: /cdn\.botpress\.cloud\/webchat/, weight: 0.95 },
    ],
  },
  {
    id: 'voiceflow',
    name: 'Voiceflow',
    category: 'chat',
    description: 'Conversational agent builder',
    icon: 'voiceflow',
    website: 'https://voiceflow.com',
    signals: [
      { type: 'global', path: 'voiceflow', weight: 0.9 },
      { type: 'script', pattern: /cdn\.voiceflow\.com\/widget/, weight: 0.95 },
    ],
  },
  {
    id: 'chatbase',
    name: 'Chatbase',
    category: 'chat',
    description: 'AI chatbots trained on your content',
    icon: 'chatbase',
    website: 'https://chatbase.co',
    signals: [
      { type: 'script', pattern: /www\.chatbase\.co\/embed(?:\.min)?\.js/, weight: 0.95 },
      { type: 'dom', selector: 'iframe[src*="chatbase.co"]', weight: 0.9 },
    ],
  },
  {
    id: 'hubspot-chat',
    name: 'HubSpot Chat',
    category: 'chat',
    description: 'Live chat bundled with HubSpot',
    icon: 'hubspot',
    website: 'https://hubspot.com/products/crm/live-chat',
    signals: [
      { type: 'global', path: 'HubSpotConversations', weight: 0.95 },
      { type: 'dom', selector: '#hubspot-messages-iframe-container', weight: 0.9 },
    ],
    implies: ['hubspot'],
  },
]
