import type { Fingerprint } from '@/types'

/**
 * Content management, site builders, and documentation.
 *
 * Traditional CMSes are among the easiest things on the web to identify —
 * WordPress announces itself in a meta generator tag and serves everything from
 * `/wp-content/`. Headless CMSes are harder, since their content arrives as
 * JSON at build time and may leave no client-side trace at all.
 */
export const CMS: Fingerprint[] = [
  {
    id: 'wordpress',
    name: 'WordPress',
    category: 'cms',
    description: 'The most widely used CMS',
    icon: 'wordpress',
    website: 'https://wordpress.org',
    implies: ['php'],
    signals: [
      { type: 'meta', name: 'generator', pattern: /WordPress/i, weight: 0.95 },
      { type: 'request', pattern: /\/wp-content\/|\/wp-includes\//, weight: 0.9 },
      { type: 'html', pattern: /\/wp-content\/(?:themes|plugins)\//, weight: 0.9 },
      { type: 'request', pattern: /\/wp-json\//, weight: 0.85 },
    ],
    version: [{ from: 'meta', name: 'generator', pattern: /WordPress\s+([\d.]+)/ }],
  },
  {
    id: 'elementor',
    name: 'Elementor',
    category: 'cms',
    description: 'WordPress page builder',
    icon: 'elementor',
    website: 'https://elementor.com',
    implies: ['wordpress'],
    signals: [
      { type: 'meta', name: 'generator', pattern: /Elementor/i, weight: 0.95 },
      { type: 'html', pattern: /elementor-(?:page|widget|section)/, weight: 0.9 },
    ],
  },
  {
    id: 'webflow',
    name: 'Webflow',
    category: 'cms',
    description: 'Visual website builder',
    icon: 'webflow',
    website: 'https://webflow.com',
    signals: [
      { type: 'meta', name: 'generator', pattern: /Webflow/i, weight: 0.95 },
      { type: 'html', pattern: /data-wf-(?:page|site|domain)/, weight: 0.9 },
      { type: 'request', pattern: /assets(?:-global)?\.website-files\.com|uploads-ssl\.webflow\.com/, weight: 0.9 },
    ],
  },
  {
    id: 'framer',
    name: 'Framer',
    category: 'cms',
    description: 'Design-first website builder',
    icon: 'framer',
    website: 'https://framer.com',
    signals: [
      { type: 'meta', name: 'generator', pattern: /Framer/i, weight: 0.95 },
      { type: 'request', pattern: /framerusercontent\.com|events\.framer\.com/, weight: 0.9 },
      { type: 'html', pattern: /__framer__|framer-[\w]{7}/, weight: 0.8 },
    ],
  },
  {
    id: 'ghost',
    name: 'Ghost',
    category: 'cms',
    description: 'Publishing platform for newsletters and blogs',
    icon: 'ghost',
    website: 'https://ghost.org',
    signals: [
      { type: 'meta', name: 'generator', pattern: /Ghost/i, weight: 0.95 },
      { type: 'script', pattern: /sodo-search|ghost\.min\.js|portal\.min\.js/, weight: 0.9 },
      { type: 'html', pattern: /ghost-portal|data-ghost/, weight: 0.8 },
    ],
    version: [{ from: 'meta', name: 'generator', pattern: /Ghost\s+([\d.]+)/ }],
  },
  {
    id: 'squarespace',
    name: 'Squarespace',
    category: 'cms',
    description: 'All-in-one website builder',
    icon: 'squarespace',
    website: 'https://squarespace.com',
    signals: [
      { type: 'global', path: 'Static.SQUARESPACE_CONTEXT', weight: 0.95 },
      { type: 'request', pattern: /static1?\.squarespace\.com|images\.squarespace-cdn\.com/, weight: 0.9 },
      { type: 'html', pattern: /squarespace-cdn|SQUARESPACE_CONTEXT/, weight: 0.9 },
    ],
  },
  {
    id: 'wix',
    name: 'Wix',
    category: 'cms',
    description: 'Website builder',
    icon: 'wix',
    website: 'https://wix.com',
    signals: [
      { type: 'meta', name: 'generator', pattern: /Wix\.com/i, weight: 0.95 },
      { type: 'request', pattern: /static\.parastorage\.com|static\.wixstatic\.com/, weight: 0.9 },
      { type: 'global', path: 'wixBiSession', weight: 0.95 },
    ],
  },
  {
    id: 'sanity',
    name: 'Sanity',
    category: 'cms',
    description: 'Headless content platform',
    icon: 'sanity',
    website: 'https://sanity.io',
    signals: [
      { type: 'request', pattern: /[\w-]+\.(?:api|apicdn)\.sanity\.io|cdn\.sanity\.io/, weight: 0.95 },
      { type: 'html', pattern: /cdn\.sanity\.io\/images/, weight: 0.85 },
    ],
  },
  {
    id: 'contentful',
    name: 'Contentful',
    category: 'cms',
    description: 'Headless CMS',
    icon: 'contentful',
    website: 'https://contentful.com',
    signals: [
      { type: 'request', pattern: /(?:cdn|preview|images)\.ctfassets\.net|(^|\.)cdn\.contentful\.com/, weight: 0.95 },
      { type: 'html', pattern: /images\.ctfassets\.net/, weight: 0.85 },
    ],
  },
  {
    id: 'strapi',
    name: 'Strapi',
    category: 'cms',
    description: 'Open-source headless CMS',
    icon: 'strapi',
    website: 'https://strapi.io',
    signals: [
      { type: 'request', pattern: /\/api\/(?:upload\/files|content-type-builder)|[\w-]+\.strapiapp\.com/, weight: 0.85 },
      { type: 'header', name: 'x-powered-by', pattern: /Strapi/i, weight: 0.95 },
    ],
  },
  {
    id: 'payload',
    name: 'Payload',
    category: 'cms',
    description: 'TypeScript headless CMS',
    icon: 'payloadcms',
    website: 'https://payloadcms.com',
    signals: [
      { type: 'request', pattern: /\/api\/(?:payload-preferences|globals)\//, weight: 0.85 },
      { type: 'bundle', pattern: /@payloadcms\/(?:next|ui)/, weight: 0.85 },
    ],
  },
  {
    id: 'prismic',
    name: 'Prismic',
    category: 'cms',
    description: 'Headless CMS with page builder',
    icon: 'prismic',
    website: 'https://prismic.io',
    signals: [
      { type: 'request', pattern: /[\w-]+\.(?:cdn\.)?prismic\.io|images\.prismic\.io/, weight: 0.95 },
    ],
  },
  {
    id: 'storyblok',
    name: 'Storyblok',
    category: 'cms',
    description: 'Headless CMS with visual editing',
    icon: 'storyblok',
    website: 'https://storyblok.com',
    signals: [
      { type: 'request', pattern: /(^|\.)api\.storyblok\.com|a\.storyblok\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'drupal',
    name: 'Drupal',
    category: 'cms',
    description: 'Enterprise open-source CMS',
    icon: 'drupal',
    website: 'https://drupal.org',
    implies: ['php'],
    signals: [
      { type: 'meta', name: 'generator', pattern: /Drupal/i, weight: 0.95 },
      { type: 'global', path: 'Drupal', weight: 0.95 },
      { type: 'html', pattern: /\/sites\/(?:default|all)\/files\/|drupal\.js/, weight: 0.85 },
    ],
  },
  {
    id: 'joomla',
    name: 'Joomla',
    category: 'cms',
    description: 'Open-source CMS',
    icon: 'joomla',
    website: 'https://joomla.org',
    implies: ['php'],
    signals: [
      { type: 'meta', name: 'generator', pattern: /Joomla/i, weight: 0.95 },
      { type: 'html', pattern: /\/media\/jui\/|\/components\/com_/, weight: 0.85 },
    ],
  },
  {
    id: 'mintlify',
    name: 'Mintlify',
    category: 'cms',
    description: 'Documentation platform',
    icon: 'mintlify',
    website: 'https://mintlify.com',
    signals: [
      { type: 'request', pattern: /mintlify\.(?:com|b-cdn\.net)|mintcdn\.com/, weight: 0.95 },
      { type: 'meta', name: 'generator', pattern: /Mintlify/i, weight: 0.95 },
    ],
  },
  {
    id: 'gitbook',
    name: 'GitBook',
    category: 'cms',
    description: 'Documentation platform',
    icon: 'gitbook',
    website: 'https://gitbook.com',
    signals: [
      { type: 'request', pattern: /[\w-]+\.gitbook\.io|gitbook-\w+\.com/, weight: 0.9 },
      { type: 'meta', name: 'generator', pattern: /GitBook/i, weight: 0.95 },
    ],
  },
  {
    id: 'docusaurus',
    name: 'Docusaurus',
    category: 'cms',
    description: 'Documentation site generator',
    icon: 'docusaurus',
    website: 'https://docusaurus.io',
    implies: ['react'],
    signals: [
      { type: 'meta', name: 'generator', pattern: /Docusaurus/i, weight: 0.95 },
      { type: 'html', pattern: /docusaurus\.config|__docusaurus/, weight: 0.85 },
    ],
    version: [{ from: 'meta', name: 'generator', pattern: /Docusaurus\s+v?([\d.]+)/ }],
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'cms',
    description: 'Pages published from Notion',
    icon: 'notion',
    website: 'https://notion.so',
    signals: [
      { type: 'request', pattern: /[\w-]*\.?notion\.(?:so|site)\/|notion-static\.com/, weight: 0.9 },
    ],
  },
  {
    id: 'hugo',
    name: 'Hugo',
    category: 'cms',
    description: 'Static site generator',
    icon: 'hugo',
    website: 'https://gohugo.io',
    signals: [{ type: 'meta', name: 'generator', pattern: /Hugo/i, weight: 0.95 }],
    version: [{ from: 'meta', name: 'generator', pattern: /Hugo\s+([\d.]+)/ }],
  },
  {
    id: 'jekyll',
    name: 'Jekyll',
    category: 'cms',
    description: 'Static site generator',
    icon: 'jekyll',
    website: 'https://jekyllrb.com',
    signals: [{ type: 'meta', name: 'generator', pattern: /Jekyll/i, weight: 0.95 }],
    version: [{ from: 'meta', name: 'generator', pattern: /Jekyll\s+v?([\d.]+)/ }],
  },
  {
    id: 'bubble',
    name: 'Bubble',
    category: 'cms',
    description: 'No-code application builder',
    icon: 'bubble',
    website: 'https://bubble.io',
    signals: [
      { type: 'meta', name: 'generator', pattern: /Bubble/i, weight: 0.95 },
      { type: 'request', pattern: /[\w-]*\.?bubbleapps\.io|cdn\.bubble\.io/, weight: 0.9 },
    ],
  },
  {
    id: 'carrd',
    name: 'Carrd',
    category: 'cms',
    description: 'One-page site builder',
    icon: 'carrd',
    website: 'https://carrd.co',
    signals: [
      { type: 'meta', name: 'generator', pattern: /Carrd/i, weight: 0.95 },
      { type: 'request', pattern: /[\w-]*\.?carrd\.co/, weight: 0.85 },
    ],
  },
  {
    id: 'typo3',
    name: 'TYPO3',
    category: 'cms',
    description: 'Enterprise open-source CMS',
    icon: 'typo3',
    website: 'https://typo3.org',
    implies: ['php'],
    signals: [
      { type: 'meta', name: 'generator', pattern: /TYPO3/i, weight: 0.95 },
      { type: 'html', pattern: /\/typo3conf\/|\/typo3temp\//, weight: 0.9 },
    ],
  },
  {
    id: 'craftcms',
    name: 'Craft CMS',
    category: 'cms',
    description: 'Content management for custom sites',
    icon: 'craftcms',
    website: 'https://craftcms.com',
    implies: ['php'],
    signals: [
      { type: 'cookie', pattern: /^CraftSessionId$/, weight: 0.95 },
      { type: 'header', name: 'x-powered-by', pattern: /Craft CMS/i, weight: 0.95 },
    ],
  },
  {
    id: 'duda',
    name: 'Duda',
    category: 'cms',
    description: 'Website builder for agencies',
    icon: 'duda',
    website: 'https://duda.co',
    signals: [
      { type: 'global', path: 'dmAPI', weight: 0.95 },
      { type: 'request', pattern: /static\.cdn-website\.com|irp\.cdn-website\.com/, weight: 0.9 },
    ],
  },
]
