import type { Fingerprint } from '@/types'

/**
 * Databases and backend-as-a-service platforms.
 *
 * Detectability splits sharply here. Platforms designed to be queried straight
 * from the browser — Supabase, Firebase, Convex, Appwrite — are highly visible.
 * Traditional databases reached only through a server (Neon, PlanetScale,
 * Postgres) are effectively invisible, and are listed for the cases where a
 * connection host does leak into client code rather than out of optimism.
 */
export const DATABASE: Fingerprint[] = [
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'database',
    description: 'Postgres database, auth, and storage',
    icon: 'supabase',
    website: 'https://supabase.com',
    signals: [
      { type: 'request', pattern: /[\w-]+\.supabase\.(?:co|in|net)\//, weight: 0.95 },
      { type: 'storage', pattern: /^sb-[\w-]+-auth-token/, weight: 0.9 },
      { type: 'global', path: 'supabase', weight: 0.8 },
      { type: 'bundle', pattern: /@supabase\/(?:supabase-js|postgrest-js|auth-js)/, weight: 0.8 },
      { type: 'request', pattern: /\/rest\/v1\/[\w-]+\?/, weight: 0.5 },
    ],
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'database',
    description: "Google's app development platform",
    icon: 'firebase',
    website: 'https://firebase.google.com',
    signals: [
      { type: 'request', pattern: /firestore\.googleapis\.com/, weight: 0.95 },
      { type: 'request', pattern: /[\w-]+\.firebaseio\.com/, weight: 0.95 },
      { type: 'request', pattern: /firebasedatabase\.app/, weight: 0.9 },
      { type: 'global', path: 'firebase', weight: 0.85 },
      { type: 'script', pattern: /firebasejs|firebase-app/, weight: 0.9 },
    ],
  },
  {
    id: 'convex',
    name: 'Convex',
    category: 'database',
    description: 'Reactive backend and database',
    icon: 'convex',
    website: 'https://convex.dev',
    signals: [
      { type: 'request', pattern: /[\w-]+\.convex\.(?:cloud|site)\//, weight: 0.95 },
      { type: 'bundle', pattern: /convex\/(?:react|browser)|ConvexReactClient/, weight: 0.85 },
    ],
  },
  {
    id: 'appwrite',
    name: 'Appwrite',
    category: 'database',
    description: 'Open-source backend platform',
    icon: 'appwrite',
    website: 'https://appwrite.io',
    signals: [
      { type: 'request', pattern: /cloud\.appwrite\.io|[\w-]+\.appwrite\.(?:io|global)/, weight: 0.95 },
      { type: 'bundle', pattern: /appwrite(?:\/dist)?\/.*Client|node-appwrite/, weight: 0.75 },
    ],
  },
  {
    id: 'pocketbase',
    name: 'PocketBase',
    category: 'database',
    description: 'Open-source backend in a single file',
    icon: 'pocketbase',
    website: 'https://pocketbase.io',
    signals: [
      { type: 'global', path: 'PocketBase', weight: 0.9 },
      { type: 'request', pattern: /\/api\/collections\/[\w-]+\/records/, weight: 0.85 },
      { type: 'storage', pattern: /^pocketbase_auth$/, weight: 0.9 },
    ],
  },
  {
    id: 'upstash',
    name: 'Upstash',
    category: 'database',
    description: 'Serverless Redis and Kafka',
    icon: 'upstash',
    website: 'https://upstash.com',
    signals: [
      { type: 'request', pattern: /[\w-]+\.upstash\.io\//, weight: 0.95 },
      { type: 'bundle', pattern: /@upstash\/(?:redis|ratelimit|vector)/, weight: 0.8 },
    ],
  },
  {
    id: 'neon',
    name: 'Neon',
    category: 'database',
    description: 'Serverless Postgres',
    icon: 'neon',
    website: 'https://neon.tech',
    signals: [
      { type: 'request', pattern: /[\w-]+\.[\w-]+\.(?:aws\.)?neon\.tech/, weight: 0.9 },
      { type: 'bundle', pattern: /@neondatabase\/serverless/, weight: 0.8 },
    ],
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    category: 'database',
    description: 'Serverless MySQL platform',
    icon: 'planetscale',
    website: 'https://planetscale.com',
    signals: [
      { type: 'request', pattern: /[\w-]+\.[\w-]+\.psdb\.cloud/, weight: 0.9 },
      { type: 'bundle', pattern: /@planetscale\/database/, weight: 0.8 },
    ],
  },
  {
    id: 'turso',
    name: 'Turso',
    category: 'database',
    description: 'Edge-hosted SQLite',
    icon: 'turso',
    website: 'https://turso.tech',
    signals: [
      { type: 'request', pattern: /[\w-]+\.turso\.io\//, weight: 0.9 },
      { type: 'bundle', pattern: /@libsql\/client/, weight: 0.8 },
    ],
  },
  {
    id: 'mongodb-atlas',
    name: 'MongoDB Atlas',
    category: 'database',
    description: 'Managed MongoDB',
    icon: 'mongodb',
    website: 'https://mongodb.com/atlas',
    signals: [
      { type: 'request', pattern: /data\.mongodb-api\.com|[\w-]+\.realm\.mongodb\.com/, weight: 0.95 },
      { type: 'bundle', pattern: /realm-web|mongodb-stitch/, weight: 0.8 },
    ],
  },
  {
    id: 'hasura',
    name: 'Hasura',
    category: 'database',
    description: 'Instant GraphQL over a database',
    icon: 'hasura',
    website: 'https://hasura.io',
    signals: [
      { type: 'request', pattern: /[\w-]+\.hasura\.app\//, weight: 0.95 },
      { type: 'header', name: 'x-hasura-role', weight: 0.9 },
    ],
  },
  {
    id: 'nhost',
    name: 'Nhost',
    category: 'database',
    description: 'Postgres backend with GraphQL',
    icon: 'nhost',
    website: 'https://nhost.io',
    signals: [{ type: 'request', pattern: /[\w-]+\.[\w-]+\.nhost\.run\//, weight: 0.95 }],
  },
  {
    id: 'xata',
    name: 'Xata',
    category: 'database',
    description: 'Serverless database platform',
    icon: 'xata',
    website: 'https://xata.io',
    signals: [
      { type: 'request', pattern: /[\w-]+\.[\w-]+\.xata\.sh|(^|\.)api\.xata\.io/, weight: 0.95 },
    ],
  },
  {
    id: 'instantdb',
    name: 'InstantDB',
    category: 'database',
    description: 'Realtime client-side database',
    icon: 'instantdb',
    website: 'https://instantdb.com',
    signals: [
      { type: 'request', pattern: /(^|\.)api\.instantdb\.com/, weight: 0.95 },
      { type: 'bundle', pattern: /@instantdb\/(?:react|core)/, weight: 0.85 },
    ],
  },
  {
    id: 'prisma-postgres',
    name: 'Prisma',
    category: 'database',
    description: 'ORM and managed Postgres',
    icon: 'prisma',
    website: 'https://prisma.io',
    signals: [
      { type: 'request', pattern: /accelerate\.prisma-data\.net/, weight: 0.95 },
      { type: 'bundle', pattern: /@prisma\/client/, weight: 0.75 },
    ],
  },
  {
    id: 'fauna',
    name: 'Fauna',
    category: 'database',
    description: 'Distributed document database',
    icon: 'fauna',
    website: 'https://fauna.com',
    signals: [{ type: 'request', pattern: /db\.fauna\.com|graphql\.fauna\.com/, weight: 0.95 }],
  },
  {
    id: 'tinybird',
    name: 'Tinybird',
    category: 'database',
    description: 'Realtime analytics over ClickHouse',
    icon: 'tinybird',
    website: 'https://tinybird.co',
    signals: [
      { type: 'request', pattern: /(^|\.)api\.(?:[\w-]+\.)?tinybird\.co/, weight: 0.95 },
    ],
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    category: 'database',
    description: 'Distributed SQL database',
    icon: 'cockroachlabs',
    website: 'https://cockroachlabs.com',
    signals: [{ type: 'request', pattern: /[\w-]+\.cockroachlabs\.cloud/, weight: 0.9 }],
  },
  {
    id: 'surrealdb',
    name: 'SurrealDB',
    category: 'database',
    description: 'Multi-model database',
    icon: 'surrealdb',
    website: 'https://surrealdb.com',
    signals: [
      { type: 'request', pattern: /[\w-]+\.surreal\.cloud|\/rpc.{0,10}surreal/i, weight: 0.9 },
      { type: 'bundle', pattern: /surrealdb\.js|@surrealdb\//, weight: 0.8 },
    ],
  },
  {
    id: 'dynamodb',
    name: 'Amazon DynamoDB',
    category: 'database',
    description: 'Managed NoSQL database on AWS',
    icon: 'amazondynamodb',
    website: 'https://aws.amazon.com/dynamodb',
    signals: [{ type: 'request', pattern: /dynamodb\.[\w-]+\.amazonaws\.com/, weight: 0.95 }],
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'database',
    description: 'In-memory data store',
    icon: 'redis',
    website: 'https://redis.io',
    signals: [{ type: 'request', pattern: /[\w-]+\.redns\.redis-cloud\.com|[\w-]+\.redislabs\.com/, weight: 0.9 },],
  },
  {
    id: 'singlestore',
    name: 'SingleStore',
    category: 'database',
    description: 'Realtime analytics database',
    icon: 'singlestore',
    website: 'https://singlestore.com',
    signals: [{ type: 'request', pattern: /[\w-]+\.singlestore\.com|svc-[\w-]+\.svc\.singlestore\.com/, weight: 0.9 }],
  },
]
