import type { Fingerprint } from '@/types'

/**
 * Forms, scheduling, and embedded widgets.
 *
 * Nearly always embedded as an iframe or a script-injected widget, which makes
 * them straightforward to spot and common enough on real SaaS sites to be worth
 * covering.
 */
export const FORMS: Fingerprint[] = [
  {
    id: 'typeform',
    name: 'Typeform',
    category: 'forms',
    description: 'Conversational forms and surveys',
    icon: 'typeform',
    website: 'https://typeform.com',
    signals: [
      { type: 'script', pattern: /embed\.typeform\.com/, weight: 0.95 },
      { type: 'dom', selector: '[data-tf-live], iframe[src*="typeform.com"]', weight: 0.9 },
      { type: 'request', pattern: /[\w-]*\.?typeform\.com/, weight: 0.85 },
    ],
  },
  {
    id: 'tally',
    name: 'Tally',
    category: 'forms',
    description: 'Free form builder',
    icon: 'tally',
    website: 'https://tally.so',
    signals: [
      { type: 'script', pattern: /tally\.so\/widgets\/embed\.js/, weight: 0.95 },
      { type: 'dom', selector: 'iframe[src*="tally.so"]', weight: 0.9 },
    ],
  },
  {
    id: 'calendly',
    name: 'Calendly',
    category: 'forms',
    description: 'Meeting scheduling',
    icon: 'calendly',
    website: 'https://calendly.com',
    signals: [
      { type: 'global', path: 'Calendly', weight: 0.95 },
      { type: 'script', pattern: /assets\.calendly\.com/, weight: 0.95 },
      { type: 'dom', selector: '.calendly-inline-widget, iframe[src*="calendly.com"]', weight: 0.9 },
    ],
  },
  {
    id: 'cal-com',
    name: 'Cal.com',
    category: 'forms',
    description: 'Open-source scheduling',
    icon: 'caldotcom',
    website: 'https://cal.com',
    signals: [
      { type: 'global', path: 'Cal', weight: 0.9 },
      { type: 'script', pattern: /(?:app\.)?cal\.com\/embed(?:\/embed)?\.js/, weight: 0.95 },
      { type: 'dom', selector: 'iframe[src*="cal.com"]', weight: 0.85 },
    ],
  },
  {
    id: 'google-forms',
    name: 'Google Forms',
    category: 'forms',
    description: 'Embedded Google form',
    icon: 'googleforms',
    website: 'https://forms.google.com',
    signals: [
      { type: 'dom', selector: 'iframe[src*="docs.google.com/forms"]', weight: 0.95 },
      { type: 'request', pattern: /docs\.google\.com\/forms\//, weight: 0.9 },
    ],
  },
  {
    id: 'formspree',
    name: 'Formspree',
    category: 'forms',
    description: 'Form backend without a server',
    icon: 'formspree',
    website: 'https://formspree.io',
    signals: [
      { type: 'dom', selector: 'form[action*="formspree.io"]', weight: 0.95 },
      { type: 'request', pattern: /formspree\.io\/[fp]\//, weight: 0.95 },
    ],
  },
  {
    id: 'chilipiper',
    name: 'Chili Piper',
    category: 'forms',
    description: 'Inbound lead routing and scheduling',
    icon: 'chilipiper',
    website: 'https://chilipiper.com',
    signals: [
      { type: 'global', path: 'ChiliPiper', weight: 0.95 },
      { type: 'script', pattern: /js\.chilipiper\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'recaptcha',
    name: 'reCAPTCHA',
    category: 'forms',
    description: 'Bot protection by Google',
    icon: 'google',
    website: 'https://google.com/recaptcha',
    signals: [
      { type: 'global', path: 'grecaptcha', weight: 0.95 },
      { type: 'script', pattern: /www\.(?:google|recaptcha\.net)\.com\/recaptcha\//, weight: 0.95 },
    ],
  },
  {
    id: 'turnstile',
    name: 'Cloudflare Turnstile',
    category: 'forms',
    description: 'Privacy-friendly CAPTCHA alternative',
    icon: 'cloudflare',
    website: 'https://cloudflare.com/products/turnstile',
    signals: [
      { type: 'global', path: 'turnstile', weight: 0.95 },
      { type: 'script', pattern: /challenges\.cloudflare\.com\/turnstile/, weight: 0.95 },
    ],
  },
  {
    id: 'hcaptcha',
    name: 'hCaptcha',
    category: 'forms',
    description: 'Privacy-focused CAPTCHA',
    icon: 'hcaptcha',
    website: 'https://hcaptcha.com',
    signals: [
      { type: 'global', path: 'hcaptcha', weight: 0.95 },
      { type: 'script', pattern: /(?:js|newassets)\.hcaptcha\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'jotform',
    name: 'Jotform',
    category: 'forms',
    description: 'Online form builder',
    icon: 'jotform',
    website: 'https://jotform.com',
    signals: [
      { type: 'dom', selector: 'iframe[src*="jotform.com"]', weight: 0.95 },
      { type: 'script', pattern: /(?:cdn|js)\.jotfor\.ms|form\.jotform\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'hubspot-forms',
    name: 'HubSpot Forms',
    category: 'forms',
    description: 'Embedded lead capture forms',
    icon: 'hubspot',
    website: 'https://hubspot.com',
    implies: ['hubspot'],
    signals: [{ type: 'script', pattern: /js\.hsforms\.net|forms\.hsforms\.com/, weight: 0.95 }],
  },
  {
    id: 'fillout',
    name: 'Fillout',
    category: 'forms',
    description: 'Form and survey builder',
    icon: 'fillout',
    website: 'https://fillout.com',
    signals: [
      { type: 'script', pattern: /server\.fillout\.com\/embed/, weight: 0.95 },
      { type: 'dom', selector: '[data-fillout-id]', weight: 0.9 },
    ],
  },
  {
    id: 'savvycal',
    name: 'SavvyCal',
    category: 'forms',
    description: 'Scheduling links',
    icon: 'savvycal',
    website: 'https://savvycal.com',
    signals: [{ type: 'script', pattern: /embed\.savvycal\.com/, weight: 0.95 }],
  },
  {
    id: 'gravity-forms',
    name: 'Gravity Forms',
    category: 'forms',
    description: 'WordPress form builder',
    icon: 'gravityforms',
    website: 'https://gravityforms.com',
    signals: [
      { type: 'script', pattern: /gravityforms\/(?:js|assets)|gform_/, weight: 0.9 },
      { type: 'dom', selector: '.gform_wrapper, form[id^="gform_"]', weight: 0.95 },
    ],
    implies: ['wordpress'],
  },
  {
    id: 'wpforms',
    name: 'WPForms',
    category: 'forms',
    description: 'WordPress drag-and-drop forms',
    icon: 'wpforms',
    website: 'https://wpforms.com',
    signals: [
      { type: 'script', pattern: /plugins\/wpforms[\w-]*\/assets/, weight: 0.95 },
      { type: 'dom', selector: '.wpforms-container, form.wpforms-form', weight: 0.95 },
    ],
    implies: ['wordpress'],
  },
  {
    id: 'contact-form-7',
    name: 'Contact Form 7',
    category: 'forms',
    description: 'The classic WordPress contact form',
    icon: 'wordpress',
    website: 'https://contactform7.com',
    signals: [
      { type: 'script', pattern: /plugins\/contact-form-7\/includes/, weight: 0.95 },
      { type: 'dom', selector: '.wpcf7, .wpcf7-form', weight: 0.95 },
    ],
    implies: ['wordpress'],
  },
  {
    id: 'paperform',
    name: 'Paperform',
    category: 'forms',
    description: 'Forms that read like documents',
    icon: 'paperform',
    website: 'https://paperform.co',
    signals: [
      { type: 'script', pattern: /paperform\.co\/__embed/, weight: 0.95 },
      { type: 'dom', selector: '[data-paperform-id]', weight: 0.95 },
    ],
  },
  {
    id: 'docusign',
    name: 'DocuSign',
    category: 'forms',
    description: 'Electronic signatures',
    icon: 'docusign',
    website: 'https://docusign.com',
    signals: [
      { type: 'request', pattern: /(?:na\d|eu|demo)\.docusign\.net|app\.docusign\.com/, weight: 0.95 },
      { type: 'dom', selector: 'iframe[src*="docusign"]', weight: 0.9 },
    ],
  },
  {
    id: 'pandadoc',
    name: 'PandaDoc',
    category: 'forms',
    description: 'Documents, proposals, and signatures',
    icon: 'pandadoc',
    website: 'https://pandadoc.com',
    signals: [
      { type: 'request', pattern: /app\.pandadoc\.com|api\.pandadoc\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'dropbox-sign',
    name: 'Dropbox Sign',
    category: 'forms',
    description: 'Electronic signatures, formerly HelloSign',
    icon: 'dropbox',
    website: 'https://sign.dropbox.com',
    signals: [
      { type: 'request', pattern: /app\.hellosign\.com|api\.hellosign\.com/, weight: 0.95 },
      { type: 'global', path: 'HelloSign', weight: 0.9 },
    ],
  },
  {
    id: 'youform',
    name: 'Youform',
    category: 'forms',
    description: 'Conversational form builder',
    icon: 'youform',
    website: 'https://youform.com',
    signals: [
      { type: 'script', pattern: /app\.youform\.com\/embed/, weight: 0.95 },
    ],
  },
  {
    id: 'zcal',
    name: 'Zcal',
    category: 'forms',
    description: 'Scheduling pages',
    icon: 'zcal',
    website: 'https://zcal.co',
    signals: [
      { type: 'dom', selector: 'iframe[src*="zcal.co"], .zcal-inline-widget', weight: 0.9 },
      { type: 'request', pattern: /zcal\.co\/(?:embed|i)\//, weight: 0.95 },
    ],
  },
]
