import type { Fingerprint } from '@/types'

/**
 * Payment processors.
 *
 * The single most reliable category. PCI requirements push card entry into a
 * provider-hosted iframe, so the provider's script and frame are always present
 * on any page that takes money — there is no server-side-only way to do this.
 */
export const PAYMENTS: Fingerprint[] = [
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'payments',
    description: 'Payments, billing, and subscriptions',
    icon: 'stripe',
    website: 'https://stripe.com',
    signals: [
      { type: 'global', path: 'Stripe', weight: 0.95 },
      { type: 'script', pattern: /js\.stripe\.com/, weight: 0.95 },
      { type: 'request', pattern: /(?:^|\.)(?:api|js|m|r|checkout)\.stripe\.com/, weight: 0.9 },
      { type: 'cookie', pattern: /^__stripe_(?:mid|sid)$/, weight: 0.9 },
      { type: 'dom', selector: 'iframe[name^="__privateStripeFrame"]', weight: 0.9 },
    ],
  },
  {
    id: 'paddle',
    name: 'Paddle',
    category: 'payments',
    description: 'Merchant of record for software',
    icon: 'paddle',
    website: 'https://paddle.com',
    signals: [
      { type: 'global', path: 'Paddle', weight: 0.95 },
      { type: 'script', pattern: /(?:cdn|buy)\.paddle\.com/, weight: 0.95 },
      { type: 'request', pattern: /checkout-service\.paddle\.com|(^|\.)api\.paddle\.com/, weight: 0.9 },
    ],
  },
  {
    id: 'lemon-squeezy',
    name: 'Lemon Squeezy',
    category: 'payments',
    description: 'Merchant of record for digital products',
    icon: 'lemonsqueezy',
    website: 'https://lemonsqueezy.com',
    signals: [
      { type: 'global', path: 'LemonSqueezy', weight: 0.95 },
      { type: 'script', pattern: /lemonsqueezy|lmsqueezy/, weight: 0.9 },
      { type: 'request', pattern: /[\w-]*\.?lemonsqueezy\.com\//, weight: 0.9 },
    ],
  },
  {
    id: 'polar',
    name: 'Polar',
    category: 'payments',
    description: 'Monetization for developers',
    icon: 'polar',
    website: 'https://polar.sh',
    signals: [
      { type: 'request', pattern: /(^|\.)api\.polar\.sh|buy\.polar\.sh/, weight: 0.95 },
      { type: 'bundle', pattern: /@polar-sh\/(?:sdk|checkout)/, weight: 0.85 },
    ],
  },
  {
    id: 'paypal',
    name: 'PayPal',
    category: 'payments',
    description: 'Online payments and checkout',
    icon: 'paypal',
    website: 'https://paypal.com',
    signals: [
      { type: 'global', path: 'paypal', weight: 0.9 },
      { type: 'script', pattern: /www\.paypal\.com\/sdk\/js|paypalobjects\.com/, weight: 0.9 },
      { type: 'request', pattern: /(?:^|\.)(?:www|api-m)\.paypal\.com\//, weight: 0.85 },
    ],
  },
  {
    id: 'razorpay',
    name: 'Razorpay',
    category: 'payments',
    description: 'Payments for Indian businesses',
    icon: 'razorpay',
    website: 'https://razorpay.com',
    signals: [
      { type: 'global', path: 'Razorpay', weight: 0.95 },
      { type: 'script', pattern: /checkout\.razorpay\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'square',
    name: 'Square',
    category: 'payments',
    description: 'Payments and point of sale',
    icon: 'square',
    website: 'https://squareup.com',
    signals: [
      { type: 'global', path: 'Square', weight: 0.9 },
      { type: 'script', pattern: /web\.squarecdn\.com|js\.squareup\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'adyen',
    name: 'Adyen',
    category: 'payments',
    description: 'Enterprise payment platform',
    icon: 'adyen',
    website: 'https://adyen.com',
    signals: [
      { type: 'global', path: 'AdyenCheckout', weight: 0.95 },
      { type: 'script', pattern: /checkoutshopper-(?:live|test)\.adyen\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'braintree',
    name: 'Braintree',
    category: 'payments',
    description: 'Payments platform owned by PayPal',
    icon: 'braintree',
    website: 'https://braintreepayments.com',
    signals: [
      { type: 'global', path: 'braintree', weight: 0.9 },
      { type: 'script', pattern: /js\.braintreegateway\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'chargebee',
    name: 'Chargebee',
    category: 'payments',
    description: 'Subscription billing and revenue',
    icon: 'chargebee',
    website: 'https://chargebee.com',
    signals: [
      { type: 'global', path: 'Chargebee', weight: 0.95 },
      { type: 'script', pattern: /js\.chargebee\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'mollie',
    name: 'Mollie',
    category: 'payments',
    description: 'European payment processing',
    icon: 'mollie',
    website: 'https://mollie.com',
    signals: [
      { type: 'global', path: 'Mollie', weight: 0.9 },
      { type: 'script', pattern: /js\.mollie\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'klarna',
    name: 'Klarna',
    category: 'payments',
    description: 'Buy now, pay later',
    icon: 'klarna',
    website: 'https://klarna.com',
    signals: [
      { type: 'global', path: 'Klarna', weight: 0.9 },
      { type: 'script', pattern: /x\.klarnacdn\.net|js\.klarna\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'afterpay',
    name: 'Afterpay',
    category: 'payments',
    description: 'Buy now, pay later',
    icon: 'afterpay',
    website: 'https://afterpay.com',
    signals: [
      { type: 'script', pattern: /static\.afterpay\.com|js\.afterpay\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'affirm',
    name: 'Affirm',
    category: 'payments',
    description: 'Pay-over-time financing',
    icon: 'affirm',
    website: 'https://affirm.com',
    signals: [
      { type: 'global', path: 'affirm', weight: 0.9 },
      { type: 'script', pattern: /cdn1?\.affirm\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'gumroad',
    name: 'Gumroad',
    category: 'payments',
    description: 'Selling digital products',
    icon: 'gumroad',
    website: 'https://gumroad.com',
    signals: [
      { type: 'script', pattern: /gumroad\.com\/js|assets\.gumroad\.com/, weight: 0.9 },
    ],
  },
  {
    id: 'revenuecat',
    name: 'RevenueCat',
    category: 'payments',
    description: 'Subscription infrastructure',
    icon: 'revenuecat',
    website: 'https://revenuecat.com',
    signals: [
      { type: 'request', pattern: /(^|\.)api\.revenuecat\.com/, weight: 0.95 },
      { type: 'bundle', pattern: /@revenuecat\/purchases-js/, weight: 0.85 },
    ],
  },
  {
    id: 'paystack',
    name: 'Paystack',
    category: 'payments',
    description: 'Payments for African businesses',
    icon: 'paystack',
    website: 'https://paystack.com',
    signals: [
      { type: 'global', path: 'PaystackPop', weight: 0.95 },
      { type: 'script', pattern: /js\.paystack\.co/, weight: 0.95 },
    ],
  },
  {
    id: 'flutterwave',
    name: 'Flutterwave',
    category: 'payments',
    description: 'Payments across Africa',
    icon: 'flutterwave',
    website: 'https://flutterwave.com',
    signals: [
      { type: 'global', path: 'FlutterwaveCheckout', weight: 0.95 },
      { type: 'script', pattern: /checkout\.flutterwave\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'mercadopago',
    name: 'Mercado Pago',
    category: 'payments',
    description: 'Payments across Latin America',
    icon: 'mercadopago',
    website: 'https://mercadopago.com',
    signals: [
      { type: 'global', path: 'MercadoPago', weight: 0.95 },
      { type: 'script', pattern: /sdk\.mercadopago\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'shopify-payments',
    name: 'Shop Pay',
    category: 'payments',
    description: "Shopify's accelerated checkout",
    icon: 'shopify',
    website: 'https://shop.app',
    implies: ['shopify'],
    signals: [
      { type: 'request', pattern: /portal\.shop\.app|pay\.shopify\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'checkout-com',
    name: 'Checkout.com',
    category: 'payments',
    description: 'Global payment processing',
    icon: 'checkoutdotcom',
    website: 'https://checkout.com',
    signals: [
      { type: 'global', path: 'Frames', weight: 0.8 },
      { type: 'request', pattern: /api\.(?:sandbox\.)?checkout\.com|cdn\.checkout\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'gocardless',
    name: 'GoCardless',
    category: 'payments',
    description: 'Bank debit payments',
    icon: 'gocardless',
    website: 'https://gocardless.com',
    signals: [
      { type: 'request', pattern: /api\.gocardless\.com|pay\.gocardless\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'recurly',
    name: 'Recurly',
    category: 'payments',
    description: 'Subscription billing',
    icon: 'recurly',
    website: 'https://recurly.com',
    signals: [
      { type: 'global', path: 'recurly', weight: 0.95 },
      { type: 'script', pattern: /js\.recurly\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'worldpay',
    name: 'Worldpay',
    category: 'payments',
    description: 'Enterprise payment processing',
    icon: 'worldpay',
    website: 'https://worldpay.com',
    signals: [
      { type: 'request', pattern: /(?:secure|api)\.worldpay\.com|payments\.worldpay\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'xendit',
    name: 'Xendit',
    category: 'payments',
    description: 'Payments across Southeast Asia',
    icon: 'xendit',
    website: 'https://xendit.co',
    signals: [
      { type: 'request', pattern: /api\.xendit\.co|checkout\.xendit\.co/, weight: 0.95 },
    ],
  },
  {
    id: 'cashfree',
    name: 'Cashfree',
    category: 'payments',
    description: 'Payments and payouts in India',
    icon: 'cashfree',
    website: 'https://cashfree.com',
    signals: [
      { type: 'global', path: 'Cashfree', weight: 0.9 },
      { type: 'script', pattern: /sdk\.cashfree\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'bolt-checkout',
    name: 'Bolt',
    category: 'payments',
    description: 'One-click checkout',
    icon: 'bolt',
    website: 'https://bolt.com',
    signals: [
      { type: 'global', path: 'BoltCheckout', weight: 0.95 },
      { type: 'script', pattern: /connect\.bolt\.com|connect-sandbox\.bolt\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'dodo-payments',
    name: 'Dodo Payments',
    category: 'payments',
    description: 'Merchant of record for digital products',
    icon: 'dodopayments',
    website: 'https://dodopayments.com',
    signals: [
      { type: 'request', pattern: /(?:live|test)\.dodopayments\.com|checkout\.dodopayments\.com/, weight: 0.95 },
    ],
  },
  {
    id: 'creem',
    name: 'Creem',
    category: 'payments',
    description: 'Payments and billing for SaaS',
    icon: 'creem',
    website: 'https://creem.io',
    signals: [
      { type: 'request', pattern: /(?:api|www)\.creem\.io\/(?:v\d|payment)/, weight: 0.95 },
    ],
  },
]
