/**
 * Compiles the privacy policy into the extension.
 *
 * The settings page used to link to the policy on GitHub — in a private
 * repository, so the link 404'd for every user who clicked it. Hosting it
 * somewhere would fix that link and still leave the policy unreadable to anyone
 * offline, and still leave two copies to drift apart.
 *
 * So the policy ships inside the extension, generated from the same
 * `store/privacy-policy.md` that gets submitted to the store. One source of
 * truth, always reachable, and the Chrome Web Store's own required policy URL
 * points at the same text.
 *
 * Parsing happens here rather than at runtime: the panel has no business
 * carrying a markdown renderer for one static document.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'

const SOURCE = 'store/privacy-policy.md'
const OUT = 'src/privacy/policy.generated.ts'

const markdown = await readFile(SOURCE, 'utf8')

/** Inline `**bold**` and `` `code` `` become spans the page can style. */
function inline(text) {
  const parts = []
  const pattern = /\*\*([^*]+)\*\*|`([^`]+)`/g
  let last = 0
  let match
  while ((match = pattern.exec(text)) !== null) {
    if (match.index > last) parts.push({ t: 'text', v: text.slice(last, match.index) })
    if (match[1] !== undefined) parts.push({ t: 'strong', v: match[1] })
    else parts.push({ t: 'code', v: match[2] })
    last = match.index + match[0].length
  }
  if (last < text.length) parts.push({ t: 'text', v: text.slice(last) })
  return parts
}

const blocks = []
let paragraph = []
let list = []

function flushParagraph() {
  if (paragraph.length === 0) return
  blocks.push({ kind: 'p', spans: inline(paragraph.join(' ')) })
  paragraph = []
}
function flushList() {
  if (list.length === 0) return
  blocks.push({ kind: 'ul', items: list.map(inline) })
  list = []
}

for (const raw of markdown.split('\n')) {
  const line = raw.trimEnd()

  if (line.trim() === '') {
    flushParagraph()
    flushList()
    continue
  }
  const heading = /^(#{1,3})\s+(.*)$/.exec(line)
  if (heading) {
    flushParagraph()
    flushList()
    blocks.push({ kind: `h${heading[1].length}`, spans: inline(heading[2]) })
    continue
  }
  const bullet = /^[-*]\s+(.*)$/.exec(line)
  if (bullet) {
    flushParagraph()
    list.push(bullet[1])
    continue
  }
  // A continuation line of the bullet above, which the source wraps at 80 cols.
  if (list.length > 0 && /^\s+/.test(raw)) {
    list[list.length - 1] += ` ${line.trim()}`
    continue
  }
  paragraph.push(line.trim())
}
flushParagraph()
flushList()

// `_Last updated: …_` is the only italic in the source and reads as metadata.
for (const block of blocks) {
  if (block.kind !== 'p' || block.spans.length !== 1) continue
  const only = block.spans[0]
  if (only.t === 'text' && /^_.*_$/.test(only.v)) {
    block.kind = 'meta'
    only.v = only.v.slice(1, -1)
  }
}

await mkdir(resolve('src/privacy'), { recursive: true })
await writeFile(
  OUT,
  `// Generated by scripts/make-privacy.mjs from ${SOURCE} — do not edit by hand.
//
// The policy ships inside the extension so the in-product link works with no
// network and no hosting, and so there is exactly one copy of the text.

export type Span = { t: 'text' | 'strong' | 'code'; v: string }

export type Block =
  | { kind: 'h1' | 'h2' | 'h3' | 'p' | 'meta'; spans: Span[] }
  | { kind: 'ul'; items: Span[][] }

export const POLICY: Block[] = ${JSON.stringify(blocks, null, 2)}
`,
)

/*
 * A standalone page for the landing site too.
 *
 * The Chrome Web Store requires a publicly reachable privacy-policy URL, and
 * the repository is private — so a link to the file on GitHub satisfies nobody.
 * Generating a plain HTML page here means hosting `landing/` anywhere at all
 * produces that URL, from the same source as the in-extension page and the
 * document submitted to the store.
 */
const esc = (v) =>
  v.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const renderSpans = (spans) =>
  spans
    .map((s) =>
      s.t === 'strong' ? `<strong>${esc(s.v)}</strong>` : s.t === 'code' ? `<code>${esc(s.v)}</code>` : esc(s.v),
    )
    .join('')

const body = blocks
  .map((b) => {
    if (b.kind === 'ul') return `<ul>${b.items.map((i) => `<li>${renderSpans(i)}</li>`).join('')}</ul>`
    if (b.kind === 'meta') return `<p class="meta">${renderSpans(b.spans)}</p>`
    if (b.kind === 'p') return `<p>${renderSpans(b.spans)}</p>`
    return `<${b.kind}>${renderSpans(b.spans)}</${b.kind}>`
  })
  .join('\n      ')

await writeFile(
  'landing/privacy.html',
  `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>StackLens — Privacy Policy</title>
    <!-- Generated by scripts/make-privacy.mjs from ${SOURCE}. Do not edit by hand. -->
    <style>
      :root { --bg:#fff; --ink:#16161c; --muted:#6b6b76; --line:#e8e8ec; --card:#f7f7f9; }
      @media (prefers-color-scheme: dark) {
        :root { --bg:#0b0b0f; --ink:#f2f2f5; --muted:#8b8b96; --line:#23232b; --card:#16161c; }
      }
      html { color-scheme: light dark; }
      body { margin:0; background:var(--bg); color:var(--muted); line-height:1.6;
             font-family: ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
             -webkit-font-smoothing: antialiased; }
      main { max-width: 42rem; margin: 0 auto; padding: 56px 24px 96px; }
      h1 { color:var(--ink); font-size:26px; letter-spacing:-0.02em; margin:0; }
      h2 { color:var(--ink); font-size:17px; margin:36px 0 0; }
      h3 { color:var(--ink); font-size:15px; margin:24px 0 0; }
      p { margin:12px 0 0; font-size:15px; }
      p.meta { color:var(--muted); font-size:13px; margin-top:4px; }
      ul { margin:12px 0 0; padding-left:18px; font-size:15px; }
      li { margin:8px 0; }
      strong { color:var(--ink); font-weight:600; }
      code { background:var(--card); border-radius:4px; padding:1px 5px; font-size:13px; color:var(--ink); }
      footer { margin-top:48px; padding-top:20px; border-top:1px solid var(--line); font-size:13px; }
      a { color:inherit; }
    </style>
  </head>
  <body>
    <main>
      ${body}
      <footer>
        The same text ships inside the extension, reachable offline from
        Settings. <a href="./index.html">StackLens</a>
      </footer>
    </main>
  </body>
</html>
`,
)

console.log(`${OUT} — ${blocks.length} blocks from ${SOURCE}`)
console.log('landing/privacy.html — hostable copy for the store\u2019s policy URL')
